# Generated by Django 4.1.2 on 2022-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mention',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
