# Generated by Django 4.1.2 on 2022-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='Нет информации', max_length=200),
        ),
    ]
