# Generated by Django 4.1.2 on 2022-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_movie_already_seen_alter_movie_want_to_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='seen_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='seen_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
