# Generated by Django 4.1.2 on 2022-10-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_session_seen_at_movie_seen_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_guild_seen_at_none',
        ),
    ]
