# Generated by Django 4.1.2 on 2022-10-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('actors', models.CharField(default='Нет информации', max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('image', models.CharField(default=None, max_length=450, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=400, null=True)),
                ('mention', models.CharField(max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ManyToManyField(default=[], related_name='+', to='core.user')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guild')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_rankings', to='core.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rankings', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='already_seen',
            field=models.ManyToManyField(blank=True, related_name='already_seen', to='core.user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guild'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rankings',
            field=models.ManyToManyField(through='core.Ranking', to='core.user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='want_to_see',
            field=models.ManyToManyField(blank=True, related_name='want_to_see', to='core.user'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('seen_at', None)), fields=('guild', 'seen_at'), name='unique_guild_seen_at_none'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('uuid', 'guild')},
        ),
    ]
