# Generated by Django 4.1.2 on 2022-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Guild',
        ),
        migrations.AlterField(
            model_name='movie',
            name='already_seen',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.user'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='want_to_see',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.user'),
        ),
    ]
