# Generated by Django 4.1.2 on 2022-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_session_unique_guild_seen_at_none_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
