# Generated by Django 4.1.2 on 2022-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dont_want_to_watch',
            field=models.ManyToManyField(blank=True, related_name='dont_want_to_watch', to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
