# Generated by Django 4.1.2 on 2023-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
