# Generated by Django 4.1.2 on 2022-10-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=None, max_length=450, null=True),
        ),
    ]
