# Generated by Django 4.1.2 on 2023-03-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chatlog_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='chat_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='core.chatlog'),
        ),
    ]
