# Generated by Django 4.1.2 on 2022-10-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ranking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ranking',
            new_name='rankings',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('movie', 'user')},
        ),
    ]
