# Generated by Django 4.1.2 on 2022-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_ranking_movie_rankings_alter_ranking_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rankings',
            field=models.ManyToManyField(through='core.Ranking', to='core.user'),
        ),
    ]
