# Generated by Django 4.1.2 on 2022-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ranking_movie_alter_ranking_user_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='already_seen',
            field=models.ManyToManyField(blank=True, related_name='already_seen', to='core.user'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='want_to_see',
            field=models.ManyToManyField(blank=True, related_name='want_to_see', to='core.user'),
        ),
    ]
