# Generated by Django 4.1.2 on 2022-10-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_session_unique_guild_seen_at_none_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.movie'),
        ),
    ]
