# Generated by Django 4.1.2 on 2022-10-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_session_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seen_at',
        ),
        migrations.AddField(
            model_name='session',
            name='seen_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.movie'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('seen_at', None)), fields=('guild', 'seen_at'), name='unique_guild_seen_at_none'),
        ),
    ]
