# Generated by Django 4.1.2 on 2022-10-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_movie_seen_at_session_seen_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
